# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'TKL_v1'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 

menu:
- {name: 'About TKL',  url: 'facts'}
# - {name: 'Learning Resources', url: 'resources'}
# - {name: 'Sample Posts',       url: 'sample-posts'}
# - {name: 'Download',            url: 'http://control.asu.edu/TKL/index.html'}
- {name: 'Documentation',      url: 'documentation'}
- {name: 'Examples',           url: 'examples'}
- {name: 'Contact',            url: 'about-the-author'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social: 
- {icon: 'download', link:    'http://control.asu.edu/TKL/index.html'}
- {icon: 'twitter', link:    'https://twitter.com/'}
- {icon: 'facebook', link:   'https://www.facebook.com/'}
- {icon: 'instagram', link:  'https://instagram.com/'}
- {icon: 'envelope', link:   'mailto:tklfeedback@asu.edu'}
- {icon: 'users', link: 'http://control.asu.edu'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
